apiVersion: apps/v1
kind: Deployment
metadata:
  name: m02-dotnet-api
  namespace: kafka
  labels:
    app: m02-dotnet-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m02-dotnet-api
  template:
    metadata:
      labels:
        app: m02-dotnet-api
    spec:
      containers:
      - name: dotnet-api
        image: m02-dotnet-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "bhf-kafka-kafka-bootstrap:9092"
        - name: ASPNETCORE_URLS
          value: "http://0.0.0.0:8080"
        - name: KAFKA_REQUEST_TIMEOUT_MS
          value: "30000"
        - name: KAFKA_DELIVERY_TIMEOUT_MS
          value: "120000"
        - name: KAFKA_RETRY_BACKOFF_MS
          value: "100"
        - name: KAFKA_RETRIES
          value: "3"
        - name: KAFKA_LINGER_MS
          value: "0"
---
apiVersion: v1
kind: Service
metadata:
  name: m02-dotnet-api
  namespace: kafka
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31081
    targetPort: 8080
  selector:
    app: m02-dotnet-api
