apiVersion: apps/v1
kind: Deployment
metadata:
  name: toxiproxy
  namespace: kafka
  labels:
    app: toxiproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toxiproxy
  template:
    metadata:
      labels:
        app: toxiproxy
    spec:
      containers:
      - name: toxiproxy
        image: ghcr.io/shopify/toxiproxy:2.9.0
        ports:
        - containerPort: 8474
        - containerPort: 29093
        livenessProbe:
          httpGet:
            path: /version
            port: 8474
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /version
            port: 8474
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: toxiproxy
  namespace: kafka
spec:
  type: NodePort
  ports:
  - name: api
    port: 8474
    nodePort: 31474
    targetPort: 8474
  - name: proxy
    port: 29093
    nodePort: 32093
    targetPort: 29093
  selector:
    app: toxiproxy
