spring:
  application:
    name: lab-01-idempotent-producer

kafka:
  bootstrap:
    servers: kafka:29092

lab:
  topic: lab01-idempotent-topic
  key: order-123
  value: '{"orderId":"order-123","amount":100.0,"status":"CREATED"}'

logging:
  level:
    com.data2ai.kafkacourse: INFO
    org.apache.kafka: WARN
